### ISSUE TITLE
ByteBuffer conversion issue during read

### ISSUE THREAD

**Issue by sonyjv** [tuplejump/calliope-release#11]
Hi Rohit, 

I have a table with collection type column.

CREATE TABLE merchant (
  id int,
  services set<text>,
  PRIMARY KEY (uid)
);

The table is populated as below
 id                                            | services
--------------------------------------+------------------------
 1                                             | {'catering', 'events'}

Defined the transformer as  
implicit def cql3Row2Merchant(keys: CQLRowKeyMap, values: CQLRowMap): Merchant = {
        Merchant(ByteBuffer2Int(keys.get("id").get), ListBB2ListString(values.get("services").toList))
    }

While retrieving the data I am getting some special characters along with list of service. 
Merchant(1, List( ? ?catering ?events))

This when converted to a json string I am getting the following output.
{"id":1, "services":["\u0000\u0002\u0000\bcatering\u0000\u0006events"]}

I presume there is something i need to do about character encoding. Can you please guide to resolve this issue. 

Also, I tried to write a List[ByteBuffer] to List[Integer] converter. 
    implicit def ListBB2ListInteger(l: List[ByteBuffer]): List[Integer] = {
        l.map(x => ByteBufferUtil.toInt(x)).map(i => i:java.lang.Integer)  
    }

But for the column Set<Int> having value {1, 2, 3, 4, 5, 6, 7}, this is returning List(458756)!!

Do you think I am missing some point. 

Thanks,
Sony

**Comment by milliondreams** [comment]
ListBB2ListString is actually meant to convert List of ByteBuffer to List of String, what we have to do here is to convert ByteBuffer of List to String, for this we will need a different transformer (which is at the moment not present in RichByteBuffer.

``` scala
implicit def ByteBuffer2ListString(buffer: ByteBuffer): List[String] = DataType.list(DataType.text()).deserialize(buffer).asInstanceOf[java.util.List[String]].asScala.toMap

```

**Comment by milliondreams** [comment]
On taking another look, noticed that its not a list but a set, so you'll need this - 

``` scala
implicit def ByteBuffer2SetString(buffer: ByteBuffer): Set[String] = DataType.set(DataType.text()).deserialize(buffer).asInstanceOf[java.util.Set[String]].asScala.toMap
```

**Comment by sonyjv** [comment]
Thanks a lot Rohit for your guidance. 

I had a look at your comments for issue https://github.com/tuplejump/calliope-release/issues/10 and following transformers worked for me.

```
implicit def ListString2ByteBuffer(list : List[String]): ByteBuffer =  DataType.list(DataType.text()).serialize(list.asJava)

implicit def ByteBuffer2ListString(buffer: ByteBuffer): List[String] = {
    DataType.list(DataType.text()).deserialize(buffer).asInstanceOf[java.util.ArrayList[String]].asScala.toList
}

implicit def ListInteger2ByteBuffer(list : List[Integer]): ByteBuffer =  DataType.list(DataType.cint()).serialize(list.asJava)

implicit def ByteBuffer2ListInteger(buffer: ByteBuffer): List[Integer] = {
    DataType.list(DataType.cint()).deserialize(buffer).asInstanceOf[java.util.ArrayList[Integer]].asScala.toList
}
```
