### ISSUE TITLE
Socket closed exceptions while writing

### ISSUE THREAD

**Issue by pezra** [tuplejump/calliope-release#14]
I am writing a bunch of data into C_. After about 15-20 thousand records i start getting "java.net.SocketException: Socket closed" exceptions (see below for stack trace). If retrying is enabled some of the retries do succeed but percentage of tasks failing due to this error increases as time goes on. In fairly short order tasks are not able to connect to C_ at all and the process dies. There are no errors in my C\* log and i am able to connect to C\* via cqlsh through the whole process.

Any ideas on what might be going wrong or what i might do about it?

PS: This is using spark in local mode with one worker and and a single node C\* running on my local box. I 

> java.io.IOException: org.apache.thrift.transport.TTransportException: java.net.SocketException: Socket closed
>   at org.apache.cassandra.hadoop.cql3.CqlRecordWriter$RangeClient.run(CqlRecordWriter.java:265)
> Caused by: org.apache.thrift.transport.TTransportException: java.net.SocketException: Socket closed
>   at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
>   at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
>   at org.apache.cassandra.thrift.TFramedTransportFactory.openTransport(TFramedTransportFactory.java:41)
>   at org.apache.cassandra.hadoop.AbstractColumnFamilyOutputFormat.createAuthenticatedClient(AbstractColumnFamilyOutputFormat.java:123)
>   at org.apache.cassandra.hadoop.cql3.CqlRecordWriter$RangeClient.run(CqlRecordWriter.java:256)
> Caused by: java.net.SocketException: Socket closed
>   at java.net.PlainSocketImpl.socketConnect(Native Method)
>   at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
>   at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
>   at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
>   at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
>   at java.net.Socket.connect(Socket.java:579)
>   at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
>   ... 4 more

**Comment by pezra** [comment]
Turns out this is [bug in Cassandra](https://issues.apache.org/jira/browse/CASSANDRA-7459).

**Comment by milliondreams** [comment]
Added the fix to latest Calliope Snapshot - 0.9.4-EA-SNAPSHOT
