### ISSUE TITLE
class file needed by Implicits is missing.

### ISSUE THREAD

**Issue by naishe** [tuplejump/calliope-release#3]
I have been trying out Calliope with Cassandra 2.0.3. Here are the setup details:

Spark: 0.8.0 Using Scala version 2.9.3 (OpenJDK 64-Bit Server VM, Java 1.7.0_45)
Cluster: 1 master, 2 slaves

Started spark as:

```
$ ADD_JARS=/root/calliope_2.9.3-0.7.3-1.jar ./spark-shell
```

 I could see the JAR is added

```
13/12/19 09:53:17 INFO spark.SparkContext: Added JAR /root/calliope_2.9.3-0.7.3-1.jar at http://10.239.3.95:35570/jars/calliope_2.9.3-0.7.3-1.jar with timestamp 1387446797286
```

When I try the example I see this following issue.

<pre>
scala> import com.tuplejump.calliope.utils.RichByteBuffer._
import com.tuplejump.calliope.utils.RichByteBuffer._

scala> import com.tuplejump.calliope.Implicits._
import com.tuplejump.calliope.Implicits._

scala> import com.tuplejump.calliope.CasBuilder
import com.tuplejump.calliope.CasBuilder

scala> val cas = CasBuilder.cql3.withColumnFamily("spark", "testsdata")
cas: com.tuplejump.calliope.Cql3CasBuilder = com.tuplejump.calliope.Cql3CasBuilder@ce10809

scala> val rdd = sc.cql3Cassandra[Map[String, String], Map[String, String]](cas)
console :21: error: class file needed by Implicits is missing.
<b>reference type SparkContext of package spark refers to nonexisting symbol.</b>
       val rdd = sc.cql3Cassandra[Map[String, String], Map[String, String]](cas)

</pre>

Can someone tell me what's wrong I am doing?

Thanks
Nishant

**Comment by milliondreams** [comment]
Hi Nishant,

This release of Calliope was compiled against Spark 0.7.3 and you are using Spark 0.8.x. The packages in spark changed upon its move to Apache and so you are seeing the ClassNotFound exception.

You could either wait for our next release to be done in Feb '14 or you could sign up to get access to our early access reposittory at http://tuplejump.github.io/calliope

**Comment by naishe** [comment]
http://tuplejjump.github.io/calliope is a 404

**Comment by naishe** [comment]
Ah there is a typo it should be  http://tuplejump.github.io/calliope

**Comment by trulite** [comment]
Thats a typo there. It is http://tuplejump.github.io/calliope

**Comment by milliondreams** [comment]
Thanks for pointing that out. Corrected!
