### ISSUE TITLE
CQL3 query generated with columns doesn't seems to be correct

### ISSUE THREAD

**Issue by NickQiZhu** [tuplejump/calliope-release#4]
I am playing with calliope with our existing log table in Cassandra 2.0.4. It seems that I can create CQL based RDD correctly if I do not use columns with CasBuilder. If I supply the columns for example:

CasBuilder.cql3.withColumnFamily("test", "logs").onHost("cassandra.local").onPort("9160").columns("message", "severity")

Then I get a runtime exception when running count on rdd. When I turned on the debug messages in spark, it showed CQL generated looks like the following:

SELECT "domain","job_id","id","List(message","severity)" FROM "logs" WHERE token("domain","job_id") > ? AND token("domain","job_id") <= ? LIMIT 1000 ALLOW FILTERING

Am I missing something here or is this a bug?

**Comment by milliondreams** [comment]
@NickQiZhu Nice catch, Was a mistake on my part!

We have fixed this in the new release. Try out 0.8.1-U1 or 0.9.0-U1-EA depending on your version of Spark.
