### ISSUE TITLE
is there any documentation for this ?

### ISSUE THREAD

**Issue by venuktan** [tuplejump/calliope-release#7]
I need to be able to access cassandra(CQL) from spark

**Comment by ra2085** [comment]
Mostly here http://tuplejump.github.com/calliope

You won't be using CQL directly, but rather build a RDD object based on parameters such as column family, colums to select, and where conditions. Mostly is self explanatory.

**Comment by ra2085** [comment]
You can also give a try to this Spark example: https://github.com/apache/incubator-spark/blob/master/examples/src/main/scala/org/apache/spark/examples/CassandraCQLTest.scala

**Comment by milliondreams** [comment]
@venuktan 

Did you fnd what you were looking for... Let me know if you still have issues working with Calliope
